# Generated by Django 6.0.7 on 2026-07-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='max_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
